#ifndef __SLICE_ERR_H__
#define __SLICE_ERR_H__

/* error codes */
#define SBI_ERR_SLICE_SUCCESS 0
#define SBI_ERR_SLICE_UNKNOWN_ERROR -1
#define SBI_ERR_SLICE_INVALID_ID -2
#define SBI_ERR_SLICE_INTERRUPTED -3
#define SBI_ERR_SLICE_PMP_FAILURE -4
#define SBI_ERR_SLICE_NOT_RUNNABLE -5
#define SBI_ERR_SLICE_NOT_DESTROYABLE -6
#define SBI_ERR_SLICE_REGION_OVERLAPS -7
#define SBI_ERR_SLICE_NOT_ACCESSIBLE -8
#define SBI_ERR_SLICE_ILLEGAL_ARGUMENT -9
#define SBI_ERR_SLICE_NOT_RUNNING -10
#define SBI_ERR_SLICE_NOT_RESUMABLE -11
#define SBI_ERR_SLICE_EDGE_CALL_HOST -12
#define SBI_ERR_SLICE_NOT_INITIALIZED -13
#define SBI_ERR_SLICE_NO_FREE_RESOURCE -14
#define SBI_ERR_SLICE_SBI_PROHIBITED -15
#define SBI_ERR_SLICE_NOT_IMPLEMENTED -16

#endif  // __SLICE_ERR_H__